DROP TABLE IF EXISTS client1.orders;
DROP TABLE IF EXISTS client1.items;
DROP TABLE IF EXISTS client2.orders;
DROP TABLE IF EXISTS client2.items;
DROP TABLE IF EXISTS users;
DROP SCHEMA IF EXISTS client1;
DROP SCHEMA IF EXISTS client2;
